### ISSUE TITLE
Problem configuring FlexSearch

### ISSUE THREAD

**Issue by ramsesgarate** [thetre97/gridsome-plugin-flexsearch#49]
I am trying to configure the plugin in my project [Repo ramsesgarate.com]( https://github.com/ramsesgarate/ramsesgarate.com).

I just installed the plugin, set it up following the prompts:

```js
{
      use: 'gridsome-plugin-flexsearch',
      options: {
        flexsearch: {
          cache: true,
          profile: 'match'
        },
        searchFields: ['title', 'tags'],
        collections: [{
          typeName: 'Post',
          indexName: 'Post',
          fields: ['title', 'description']
        }, ]
      }
    }
```

And I'm testing it in a view like so:

```html
<template>
  <Layout>
    <input
      id="search"
      v-model="searchTerm"
      class="input"
      type="text"
      placeholder="Search">
    {{ searchResults }}
  </Layout>
</template>

<script>
export default {
  data: () => ({
    searchTerm: ''
  }),
  computed: {
    searchResults () {
      const searchTerm = this.searchTerm
      if (searchTerm.length < 3) return []
      return this.$search.search({ query: searchTerm, limit: 5 })
    },
    test() {
      return this.$search();
    }
  },
  watch: {
    $route (to, from) {
      this.searchTerm = ''
    }
  }
}
</script>
```

When I run the `gridsome develop` command I get the following error:

```bash
TypeError: Object.fromEntries is not a function
    at collectionStore.data.map.node (C:\Users\AWTO\projects\ramsesgarate\node_modules\gridsome-plugin-flexsearch\gridsome.server.js:72:26)
    at Array.map (<anonymous>)
    at getStoreCollection (C:\Users\AWTO\projects\ramsesgarate\node_modules\gridsome-plugin-flexsearch\gridsome.server.js:56:35)
    at collection (C:\Users\AWTO\projects\ramsesgarate\node_modules\gridsome-plugin-flexsearch\gridsome.server.js:122:14)
    at C:\Users\AWTO\projects\ramsesgarate\node_modules\gridsome-plugin-flexsearch\node_modules\p-map\index.js:57:28
```

I can't find what the error may be, could you guide me, thanks.

**Comment by thetre97** [comment]
@ramsesgarate You will need to use  node version that is `>=12.x`.

**Comment by ramsesgarate** [comment]
Thanks man
